services:
  - type: web
    name: pdf-insight-agent
    runtime: python
    pythonVersion: "3.10.13"
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn backend.app:app --workers=2 --timeout 120 --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEEPSEEK_API_KEY
        value: your_deepseek_api_key_here
      - key: PORT
        value: 10000
